name: examiner_bigaze
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  cloud_firestore: ^5.5.0
  flutter_launcher_icons: ^0.14.1
  icons_launcher: ^3.0.0
  firebase_messaging: ^15.1.5
  multi_select_flutter: ^4.1.3
  provider: ^6.1.2
  firebase_auth: ^5.4.0
  google_sign_in: ^6.2.2
  firebase_ui_auth: ^1.16.1
  firebase_storage: ^12.4.0
  image_picker: ^1.1.2
  numberpicker: ^2.1.2
  # qr_flutter: ^4.1.0
  path_provider: ^2.1.5
  # share_plus: ^10.1.4
  # qr_code_to_image: ^0.0.3
  flutter_local_notifications: ^18.0.1
  table_calendar: ^3.1.3
  


 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  - assets/icon/time-management.png
  - assets/icon/bigaze.png
  - assets/icon/GWqs.gif
  - assets/icon/splash_image.png
  - assets/bg.gif
  - assets/icon/google.png
  - assets/plogo.png
  - assets/icon/live.gif
  - assets/icon/exam-time.png




flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/plogo.png"
  min_sdk_android: 21
  adaptive_icon_foreground: "assets/plogo.png"  # Foreground image
  adaptive_icon_background: "#000000"  # Solid black background

  
     