// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClS4S9Q19xrCivZfuKUAq0jb4vO2K9Tt8',
    appId: '1:216830322809:web:50e4d3b26345ad37128ca8',
    messagingSenderId: '216830322809',
    projectId: 'bigaze-c10db',
    authDomain: 'bigaze-c10db.firebaseapp.com',
    databaseURL: 'https://bigaze-c10db-default-rtdb.firebaseio.com',
    storageBucket: 'bigaze-c10db.appspot.com',
    measurementId: 'G-YC1Q4BP7CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASZlDDYcdU2E1d1mfrrNBDIzjfErQsq4E',
    appId: '1:216830322809:android:cefc2049ccd018cb128ca8',
    messagingSenderId: '216830322809',
    projectId: 'bigaze-c10db',
    databaseURL: 'https://bigaze-c10db-default-rtdb.firebaseio.com',
    storageBucket: 'bigaze-c10db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcVM_6SWaVB1VXI-hmqgfc_yyHKnWT6pU',
    appId: '1:216830322809:ios:78767b48435fdb2a128ca8',
    messagingSenderId: '216830322809',
    projectId: 'bigaze-c10db',
    databaseURL: 'https://bigaze-c10db-default-rtdb.firebaseio.com',
    storageBucket: 'bigaze-c10db.appspot.com',
    androidClientId: '216830322809-bd8ur767j1i61al4t30ooqe64ivft2gp.apps.googleusercontent.com',
    iosClientId: '216830322809-a57jcncb8tg1pjti1i755k2fhuuijjo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.examinerBigaze',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcVM_6SWaVB1VXI-hmqgfc_yyHKnWT6pU',
    appId: '1:216830322809:ios:78767b48435fdb2a128ca8',
    messagingSenderId: '216830322809',
    projectId: 'bigaze-c10db',
    databaseURL: 'https://bigaze-c10db-default-rtdb.firebaseio.com',
    storageBucket: 'bigaze-c10db.appspot.com',
    androidClientId: '216830322809-bd8ur767j1i61al4t30ooqe64ivft2gp.apps.googleusercontent.com',
    iosClientId: '216830322809-a57jcncb8tg1pjti1i755k2fhuuijjo9.apps.googleusercontent.com',
    iosBundleId: 'com.example.examinerBigaze',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaR2D1wxT_rrW_LAFUm0RCh7qW0QMs3zI',
    appId: '1:216830322809:web:183251c3a94d4ebb128ca8',
    messagingSenderId: '216830322809',
    projectId: 'bigaze-c10db',
    authDomain: 'bigaze-c10db.firebaseapp.com',
    databaseURL: 'https://bigaze-c10db-default-rtdb.firebaseio.com',
    storageBucket: 'bigaze-c10db.appspot.com',
    measurementId: 'G-KJQG4C95DX',
  );

}